version: "3.7"
services:
  mysql:
    privileged: true
    container_name: mysql-8.0.20
    network_mode: "bridge"
    hostname: localhost
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "chop!@#root"
      MYSQL_USER: 'visitor'
      MYSQL_PASS: 'chop!@#visitor'
    image: "mysql:8.0.20"
    restart: always
    volumes:
      - /opt/mysql/conf/my.cnf:/etc/my.cnf
      - /opt/mysql/init:/docker-entrypoint-initdb.d/
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/mysqld.log:/var/log/mysqld.log
    ports:
      - 3306:3306

