version: "3.7"
services:
  nacos:
    container_name: nacos-server-standalone
    restart: always
    image: nacos/nacos-server
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=256m
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=127.0.0.1(mysql网关地址)
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos-config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=chop!@#root
    volumes:
      - /opt/nacos/logs/:/opt/nacos/logs
      - /opt/nacos/plugins/mysql/:/home/nacos/plugins/mysql/
      - /opt/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
      - 9555:9555


